# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34d66c7a65fa8e54cf7ae5c9206e94f0ac837970e2e89d51e781c1e12e52190bea2deb3976f3f85d01bad052cf7f39562e8b68452210b763de11d231bba103a

test:
  secret_key_base: bb8eaf4f5163b480a95dbff9617037dc79201d94a73b099f3cc5c3eb430ee93c47a1a7dc5307420d7356d4221311d9ee3f7dc28c70e7c20fff980c56cef48daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
